name: multi-image-comparer-pull_request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
       go-version: '1.17.6'

    - name: Install Go Packages Pearson Correlation Coefficient
      run: cd pearson-correlation-coefficient && source setup.sh && go get -t -v github.com/stretchr/testify/assert && go get -t -v github.com/jesperancinha/images-go/points

    - name: Install Go Packages Tanimoto Correlation Coefficient
      run: cd tanimoto-correlation-coefficient && source setup.sh && go get -t -v github.com/stretchr/testify/assert && go get -t -v github.com/jesperancinha/images-go/points

    - name: Run Go Tests Pearson Correlation Coefficient
      run: cd pearson-correlation-coefficient && source setup.sh && go test -coverprofile=coverage.out

    - name: Run Go Tests Tanimoto Correlation Coefficient
      run: cd tanimoto-correlation-coefficient && source setup.sh && go test -coverprofile=coverage.out
